#include <stdio.h>
#include <string.h>

static int
has(char *want)
{
	char line[80];
	int yes;

	yes = 0;
	while(fgets(line, sizeof line, stdin) != NULL)
		if(strstr(line, want) != NULL)
			yes = 1;
	return yes;
}

int
main(void)
{
	if(!has("virtio"))
		return 1;
	printf("/* generated by mkconf from usr/sys/conf/arm_qemu */\n");
	printf("#include \"../h/param.h\"\n");
	printf("#include \"../h/acct.h\"\n");
	printf("#include \"../h/buf.h\"\n");
	printf("#include \"../h/conf.h\"\n");
	printf("#include \"../h/dir.h\"\n");
	printf("#include \"../h/file.h\"\n");
	printf("#include \"../h/filsys.h\"\n");
	printf("#include \"../h/inode.h\"\n");
	printf("#include \"../h/mount.h\"\n");
	printf("#include \"../h/proc.h\"\n");
	printf("#include \"../h/systm.h\"\n");
	printf("#include \"../h/text.h\"\n");
	printf("#include \"../h/user.h\"\n\n");
	printf("extern struct buf virtio_tab;\n");
	printf("extern int virtio_strategy(struct buf *bp);\n");
	printf("static int nulldev_dev(dev_t dev, int flag) { (void)dev; (void)flag; return 0; }\n");
	printf("dev_t rootdev = 0;\n");
	printf("int nblkdev = 0;\n");
	printf("struct bdevsw bdevsw[2] = { { nulldev_dev, nulldev_dev, virtio_strategy, &virtio_tab }, { 0, 0, 0, 0 } };\n");
	printf("struct proc proc[NPROC];\n");
	printf("struct file file[NFILE];\n");
	printf("struct inode inode[NINODE];\n");
	printf("struct text text[NTEXT];\n");
	printf("struct user u;\n");
	printf("struct buf bfreelist;\n");
	printf("struct buf buf[NBUF];\n");
	printf("struct inode *acctp;\n");
	printf("struct acct acctbuf;\n");
	printf("struct cdevsw cdevsw[1];\n");
	return 0;
}
